(() => {
  const DEFAULTS={channels:{whatsapp:true,email:true,push:false},topics:{currencies:true,equities:true,etfs:true,ratings:true,barrons:true,macro:true},minScore:80,minConviction:4,quietStart:'22:00',quietEnd:'07:00',digest:'06:00',endpoint:'https://alex-global-currency-intelligence.proadmexico.workers.dev'};
  const key='agci-alert-preferences-v2';
  const read=()=>{try{const saved=JSON.parse(localStorage.getItem(key)||'{}');return {...DEFAULTS,...saved,channels:{...DEFAULTS.channels,...saved.channels},topics:{...DEFAULTS.topics,...saved.topics}}}catch{return structuredClone(DEFAULTS)}};
  const save=v=>localStorage.setItem(key,JSON.stringify(v));
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  function build(){
    const nav=document.querySelector('.main-nav'),main=document.querySelector('main');
    if(!nav||!main||document.getElementById('alerts'))return;
    const b=document.createElement('button');b.dataset.view='alerts';b.textContent='Alerts';b.addEventListener('click',()=>typeof setView==='function'&&setView('alerts'));nav.appendChild(b);
    const p=read();
    main.insertAdjacentHTML('beforeend',`<section id="alerts" class="view alerts-view"><div class="page-head"><p class="rubric">PROACTIVE INTELLIGENCE</p><h2>AGCI Alert Center</h2><p>Executive WhatsApp intelligence for material market changes, data-governance risks and scheduled decision briefs.</p></div><div class="alerts-status"><span class="status-dot" id="alertsDot"></span><div><strong id="alertsConnection">Checking secure delivery service…</strong><small id="alertsConnectionNote">The public site reads only safe Worker status endpoints. Tokens and private API keys remain server-side.</small></div></div><form id="alertsForm" class="alerts-grid"><article><h3>Delivery channels</h3>${[['whatsapp','WhatsApp — critical alerts and briefs'],['email','Email — daily and weekly digest'],['push','Browser push — while AGCI is open']].map(([k,l])=>`<label class="alert-switch"><input type="checkbox" data-group="channels" value="${k}" ${p.channels[k]?'checked':''}><span>${l}</span></label>`).join('')}</article><article><h3>Alert topics</h3>${[['currencies','Currencies'],['equities','US equities'],['etfs','ETFs'],['ratings','Analyst ratings / CIAR'],['barrons','AGCI vs Barron’s'],['macro','Central banks and macro risk']].map(([k,l])=>`<label class="alert-switch"><input type="checkbox" data-group="topics" value="${k}" ${p.topics[k]?'checked':''}><span>${l}</span></label>`).join('')}</article><article><h3>Materiality filters</h3><label>Minimum AGCI score<input id="alertMinScore" type="number" min="0" max="100" value="${p.minScore}"></label><label>Minimum conviction<select id="alertConviction">${[1,2,3,4,5].map(n=>`<option value="${n}" ${n===p.minConviction?'selected':''}>${'★'.repeat(n)}${'☆'.repeat(5-n)}</option>`).join('')}</select></label><label>Preferred digest time<input id="alertDigest" type="time" value="${p.digest}"></label></article><article><h3>Quiet hours</h3><label>From<input id="alertQuietStart" type="time" value="${p.quietStart}"></label><label>To<input id="alertQuietEnd" type="time" value="${p.quietEnd}"></label><p class="alert-help">Critical data, availability and market alerts bypass quiet hours.</p></article><article class="alerts-endpoint"><h3>Secure delivery service</h3><label>Worker URL<input id="alertEndpoint" type="url" value="${esc(p.endpoint||'')}"></label><p class="alert-help">Cloudflare Worker → Meta WhatsApp API. The browser never receives the private sending key.</p></article></form><div class="alerts-actions"><button id="saveAlerts" type="button">Save preferences</button><button id="testAlerts" type="button" class="secondary">Verify Worker</button><span id="alertsMessage" role="status" aria-live="polite"></span></div><section class="alert-history"><div class="section-heading"><div><p class="rubric">EXECUTIVE DELIVERY</p><h2>Operational status</h2></div></div><div id="alertHistory"><p class="empty-alerts" id="alertOps">Loading automation, freshness, watchlist and storage status…</p></div></section></section>`);
    const form=document.getElementById('alertsForm'),msg=document.getElementById('alertsMessage'),dot=document.getElementById('alertsDot'),connection=document.getElementById('alertsConnection'),note=document.getElementById('alertsConnectionNote'),ops=document.getElementById('alertOps');
    const collect=()=>{const out={channels:{},topics:{},minScore:+document.getElementById('alertMinScore').value,minConviction:+document.getElementById('alertConviction').value,quietStart:document.getElementById('alertQuietStart').value,quietEnd:document.getElementById('alertQuietEnd').value,digest:document.getElementById('alertDigest').value,endpoint:document.getElementById('alertEndpoint').value.trim().replace(/\/$/,'')};form.querySelectorAll('input[type=checkbox]').forEach(x=>out[x.dataset.group][x.value]=x.checked);return out};
    const verify=async()=>{const cfg=collect();if(!cfg.endpoint){msg.textContent='Add the deployed Worker URL first.';return}msg.textContent='Checking Worker…';try{const [healthResponse,sourceResponse]=await Promise.all([fetch(`${cfg.endpoint}/health`,{headers:{accept:'application/json'}}),fetch(`${cfg.endpoint}/source-health`,{headers:{accept:'application/json'}})]);const data=await healthResponse.json().catch(()=>({}));const source=await sourceResponse.json().catch(()=>({}));if(!healthResponse.ok||!data.ok)throw new Error(`HTTP ${healthResponse.status}`);const mode=data.deliveryMode==='production'?'Production':'Test';connection.textContent=data.configured?`Worker connected — ${mode} mode`:'Worker online — setup incomplete';note.textContent=data.configured?`Template ${data.template||'not reported'} · Graph ${data.graphVersion||'configured'} · automation ${data.automationEnabled?'enabled':'safely disabled'}.`:'The Worker responds, but required Meta configuration is incomplete.';dot.classList.toggle('connected',Boolean(data.configured));const freshness=source.ok?(source.stale?`STALE · ${source.ageMinutes} min old`:(source.ageMinutes===null?'timestamp not reported':`fresh · ${source.ageMinutes} min old`)):'unavailable';ops.textContent=`Briefs: ${(data.digestTimes||[]).join(', ')||'not configured'} · Watchlist: ${data.watchlistCount||0} assets · Market source: ${freshness} · Deduplication: ${data.deduplication?'active':'binding pending'} · History: ${data.history?'active':'binding pending'}.`;msg.textContent='Worker and market-source checks completed.';save(cfg)}catch(e){connection.textContent='Connection failed';note.textContent='The Worker could not be reached from this browser.';ops.textContent='Operational status unavailable.';dot.classList.remove('connected');msg.textContent=`Verification failed: ${e.message}`}};
    document.getElementById('saveAlerts').onclick=()=>{save(collect());msg.textContent='Preferences saved on this device.'};
    document.getElementById('testAlerts').onclick=verify;
    verify();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build,{once:true});else build();
})();