(()=>{const U='viajes/viajes_data.json',P='viajes/Viajes_ASC_Resumen_Ejecutivo.pdf.b64';let D;
const m=v=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(+v||0);
const u=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(+v||0);
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function css(){if(document.querySelector('#travelCss'))return;let s=document.createElement('style');s.id='travelCss';s.textContent=`
.travel-status{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;border-block:1px solid var(--rule);padding:11px 0;margin-bottom:22px;font-size:11px;text-transform:uppercase}.travel-actions{display:flex;gap:8px}.travel-actions button{padding:9px 12px;border:1px solid var(--ink);background:var(--ink);color:var(--paper);cursor:pointer}.travel-actions .secondary{background:transparent;color:var(--ink)}
.travel-hero{display:grid;grid-template-columns:1.5fr .8fr;gap:28px;border-top:5px solid var(--ink);padding-top:18px}.travel-hero h2{font:700 50px/1.02 "Source Serif 4",serif;margin:8px 0 12px}.travel-dek{font:18px/1.5 "Source Serif 4",serif;color:var(--muted)}.travel-kpis{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--rule);border:1px solid var(--rule)}.travel-kpi{background:var(--paper);padding:15px}.travel-kpi span{font-size:9px;text-transform:uppercase;color:var(--muted)}.travel-kpi strong{display:block;font:700 27px "Source Serif 4",serif;margin-top:4px}.travel-note{margin-top:16px;padding:13px 15px;border-left:5px solid var(--blue);background:var(--soft);font-size:12px;color:var(--muted)}
.travel-head{display:flex;justify-content:space-between;align-items:end;gap:18px;border-top:4px solid var(--ink);padding-top:12px;margin-top:36px}.travel-head h3{font:700 33px "Source Serif 4",serif;margin:4px 0 10px}.travel-head p{max-width:700px;color:var(--muted);font-size:12px}
.travel-rank{display:grid;grid-template-columns:42px 1.1fr 70px 110px 110px 120px 1.5fr;gap:12px;align-items:center;border-top:1px solid var(--rule);padding:14px 7px;font-size:12px}.travel-rank:last-child{border-bottom:1px solid var(--ink)}.travel-rank:hover{background:var(--soft)}.travel-num,.travel-score{font:700 27px "Source Serif 4",serif}.travel-city strong{display:block;font:700 21px "Source Serif 4",serif}.travel-city small,.travel-rank small{color:var(--muted)}
.travel-budgets{display:grid;grid-template-columns:1fr 1fr;gap:26px}.travel-budget{border-top:4px solid var(--ink);padding-top:13px}.travel-budget h4{font:700 29px "Source Serif 4",serif;margin:2px 0}.travel-budget>p{font-size:12px;color:var(--muted)}.travel-row{display:flex;justify-content:space-between;border-top:1px solid var(--rule);padding:10px 0;font-size:12px}.travel-row.total{border-top:2px solid var(--ink);font-size:15px}
.travel-cards{display:grid;grid-template-columns:repeat(5,1fr);gap:13px}.travel-card{border:1px solid var(--rule);padding:15px}.travel-card h4{font:700 23px "Source Serif 4",serif;margin:6px 0}.travel-card b{font:700 34px "Source Serif 4",serif}.travel-card p,.travel-card dd{font-size:11px;color:var(--muted);line-height:1.4}.travel-card dt{font-size:9px;text-transform:uppercase;margin-top:8px}.travel-card dd{margin:2px 0}
.travel-method{margin-top:30px;padding:18px;border:1px solid var(--rule);background:var(--soft)}.travel-weights{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.travel-weights span{background:var(--paper);border:1px solid var(--rule);padding:10px;font-size:10px}.travel-weights b{display:block;font:700 25px "Source Serif 4",serif}
@media(max-width:1000px){.travel-cards{grid-template-columns:1fr 1fr}.travel-rank{grid-template-columns:36px 1fr 65px 100px 100px}.travel-rank>*:nth-child(6),.travel-rank>*:nth-child(7){display:none}}@media(max-width:700px){.travel-hero,.travel-budgets{grid-template-columns:1fr}.travel-hero h2{font-size:39px}.travel-cards{grid-template-columns:1fr}.travel-ranking{overflow:auto}.travel-rank{min-width:630px}.travel-weights{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(s)}
function shell(){let n=document.querySelector('.main-nav');if(n&&!n.querySelector('[data-view="travel"]')){let b=document.createElement('button');b.dataset.view='travel';b.textContent='Viajes ASC';n.insertBefore(b,n.querySelector('[data-view="briefing"]'));b.onclick=()=>setView('travel')}let s=document.querySelector('#travel');if(!s){s=document.createElement('section');s.id='travel';s.className='view';s.innerHTML='<p>Cargando Viajes ASC…</p>';document.querySelector('main').appendChild(s)}return s}
const rows=p=>[['flight','Vuelo'],['hotel','Hotel'],['food','Comidas'],['transport','Transporte'],['experiences','Experiencias'],['contingency','Contingencia']].map(([k,l])=>`<div class="travel-row"><span>${l}</span><strong>${m(p[k]?.total_mxn)}</strong></div>`).join('');
function render(d){D=d;let s=shell(),a=d.weekly_destination||{},x=d.exchange_rates||{},t=d.profiles.tourist,b=d.profiles.business,r=d.opportunity_rankings.destinations,w=d.opportunity_rankings.methodology.weights,dt=new Intl.DateTimeFormat('es-MX',{dateStyle:'long',timeStyle:'short',timeZone:'America/Mexico_City'}).format(new Date(d.meta.last_updated));
s.innerHTML=`<div class="page-head"><p class="rubric">VIAJES ASC · INTELIGENCIA TURÍSTICA FINANCIERA</p><h2>Top 5 global de oportunidades</h2><p>Calidad mundial, precio-dólar, valor hotelero y conectividad desde México.</p></div>
<div class="travel-status"><span><b>Actualización automática</b> · ${e(dt)}</span><div class="travel-actions"><button id="travelRefresh">Actualizar</button><button class="secondary" id="travelPdf">Abrir PDF</button></div></div>
<section class="travel-hero"><div><p class="rubric">DESTINO SEMANAL ACTIVO</p><h2>${e(a.city)}, ${e(a.country)}</h2><p class="travel-dek">${e(a.why_now)}</p><div class="travel-note"><b>${d.daily_deals.length?'Oportunidades activas':'Sin cambio accionable'}</b><br>${e(d.monitoring.notes)}</div></div><aside class="travel-kpis"><div class="travel-kpi"><span>Vuelo Turista</span><strong>${m(t.flight.total_mxn)}</strong></div><div class="travel-kpi"><span>Total Turista</span><strong>${m(t.total_mxn)}</strong></div><div class="travel-kpi"><span>Total Business</span><strong>${m(b.total_mxn)}</strong></div><div class="travel-kpi"><span>Tipo de cambio</span><strong>${(+x.mxn_to_local).toLocaleString('es-MX',{maximumFractionDigits:2})} ${e(x.local_currency_code)}</strong></div></aside></section>
<div class="travel-head"><div><p class="rubric">ÍNDICE ASC</p><h3>Ranking global</h3></div><p>${e(d.opportunity_rankings.methodology.note)}</p></div><div class="travel-ranking">${r.map(q=>`<article class="travel-rank"><div class="travel-num">${String(q.rank).padStart(2,'0')}</div><div class="travel-city"><strong>${e(q.city)}</strong><small>${e(q.country)} · ${e(q.global_reference)}</small></div><div><small>ASC</small><div class="travel-score">${(+q.asc_score).toFixed(1)}</div></div><div><small>Vuelo MEX</small><strong>${m(q.flight_mxn)}</strong></div><div><small>Hotel</small><strong>${u(q.hotel_avg_usd)}</strong></div><div><small>Costo base</small><strong>${m(q.base_access_mxn)}</strong></div><div>${e(q.why)}</div></article>`).join('')}</div>
<div class="travel-head"><div><p class="rubric">DESTINO ACTIVO</p><h3>Presupuesto semanal</h3></div><p>Un viajero, siete noches. Tarifas no vinculantes.</p></div><div class="travel-budgets"><article class="travel-budget"><p class="rubric">TURISTA</p><h4>${e(t.label)}</h4><p>${e(t.assumption)}</p>${rows(t)}<div class="travel-row total"><span>Total</span><strong>${m(t.total_mxn)}</strong></div></article><article class="travel-budget"><p class="rubric">BUSINESS</p><h4>${e(b.label)}</h4><p>${e(b.assumption)}</p>${rows(b)}<div class="travel-row total"><span>Total</span><strong>${m(b.total_mxn)}</strong></div></article></div>
<div class="travel-head"><div><p class="rubric">COMPARATIVO</p><h3>Lectura por destino</h3></div><p>El orden cambia solo con variaciones materiales y verificadas.</p></div><div class="travel-cards">${r.map(q=>`<article class="travel-card"><span class="rubric">#${q.rank}</span><h4>${e(q.city)}</h4><b>${(+q.asc_score).toFixed(1)}</b><p>${e(q.why)}</p><dl><dt>Moneda</dt><dd>${(+q.local_per_mxn).toLocaleString('es-MX',{maximumFractionDigits:2})} ${e(q.currency)}/MXN</dd><dt>Ruta</dt><dd>${e(q.route)}</dd><dt>Tiempo</dt><dd>${e(q.time)}</dd><dt>5 estrellas</dt><dd>${u(q.hotel_5star_usd)}/noche</dd><dt>Riesgo</dt><dd>${e(q.risk)}</dd></dl></article>`).join('')}</div>
<article class="travel-method"><p class="rubric">METODOLOGÍA</p><h3>${e(d.opportunity_rankings.methodology.name)}</h3><div class="travel-weights"><span><b>${w.global_quality_importance_pct}%</b>Calidad global</span><span><b>${w.fx_dollar_opportunity_pct}%</b>Oportunidad FX</span><span><b>${w.hotel_value_pct}%</b>Valor hotelero</span><span><b>${w.connectivity_from_mexico_pct}%</b>Conectividad</span></div></article>`;
s.querySelector('#travelRefresh').onclick=()=>load(1);s.querySelector('#travelPdf').onclick=pdf}
async function pdf(){let b=document.querySelector('#travelPdf'),z=b.textContent;b.disabled=1;b.textContent='Preparando…';try{let r=await fetch(P+'?t='+Date.now(),{cache:'no-store'}),a=atob((await r.text()).trim()),v=new Uint8Array(a.length);for(let i=0;i<a.length;i++)v[i]=a.charCodeAt(i);let o=URL.createObjectURL(new Blob([v],{type:'application/pdf'}));open(o,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(o),120000)}catch{alert('PDF no disponible temporalmente')}finally{b.disabled=0;b.textContent=z}}
async function load(f){try{let r=await fetch(U+(f?'?t='+Date.now():''),{cache:'no-store'}),d=await r.json();if(!d.opportunity_rankings)throw 0;render(d)}catch(e){console.error(e);if(!D)shell().innerHTML='<p>No fue posible cargar Viajes ASC.</p>'}}
css();shell();load(1);setInterval(()=>document.visibilityState==='visible'&&load(1),900000)})();