(() => {
  'use strict';
  if (window.__VIAJES_ASC_PDF_ENGINE__) return;
  window.__VIAJES_ASC_PDF_ENGINE__ = true;

  const core = window.TravelPdfCore;
  if (!core) { console.error('Viajes ASC Phase 9: PDF core unavailable'); return; }
  const state = { profile:null, research:null, logistics:null, itinerary:null, cost:null, selectedWindow:null, report:null };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const safeHref = value => { try { const url = new URL(String(value || '')); return url.protocol === 'https:' ? url.href : ''; } catch { return ''; } };
  const money = (amount,currency) => { if(amount===null||amount===undefined||!Number.isFinite(Number(amount)))return'—';try{return new Intl.NumberFormat('es-MX',{style:'currency',currency:currency||'USD',maximumFractionDigits:0}).format(Number(amount));}catch{return`${Number(amount)} ${currency||''}`;} };
  const fmtDate = value => { try { return new Intl.DateTimeFormat('es-MX',{day:'2-digit',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`)); } catch { return value || '—'; } };
  const fmtTime = stop => !stop?.time ? 'Horario por confirmar' : `${String(Math.floor(stop.time.start/60)%24).padStart(2,'0')}:${String(stop.time.start%60).padStart(2,'0')}${stop.time.end!==null?`–${String(Math.floor(stop.time.end/60)%24).padStart(2,'0')}:${String(stop.time.end%60).padStart(2,'0')}`:''}`;

  function styles(){
    if(document.getElementById('viajes-phase9-styles'))return;
    const style=document.createElement('style');style.id='viajes-phase9-styles';
    style.textContent=`.asc-pdf{margin-top:18px;border:1px solid rgba(232,198,106,.28);border-radius:18px;background:linear-gradient(145deg,rgba(17,16,10,.94),rgba(5,11,16,.88));overflow:hidden}.asc-pdf[hidden]{display:none}.asc-pdf__head{padding:22px 24px;border-bottom:1px solid #2c2b23}.asc-pdf__head p{color:#e8c66a;font:700 9px/1.3 ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase}.asc-pdf__head h2{margin-top:7px;color:#fff;font-size:23px}.asc-pdf__head span{display:block;margin-top:7px;color:#9aa3af;font-size:11px;line-height:1.55}.asc-pdf__status{padding:13px 24px;border-bottom:1px solid #2c2b23;color:#94a3b8;font-size:11px}.asc-pdf__status[data-state=ready]{color:#86efac}.asc-pdf__metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1px;background:#2c2b23}.asc-pdf__metrics div{padding:14px;background:#0c131a}.asc-pdf__metrics span{display:block;color:#64748b;font:700 8px/1.2 ui-monospace,monospace;text-transform:uppercase}.asc-pdf__metrics strong{display:block;margin-top:5px;color:#fff;font-size:15px}.asc-pdf__actions{display:flex;flex-wrap:wrap;gap:9px;padding:18px 24px}.asc-pdf__actions button{border:1px solid #475569;border-radius:8px;padding:10px 13px;background:#0a141d;color:#dbe6f1;font:700 10px/1.2 ui-monospace,monospace;cursor:pointer}.asc-pdf__actions button:first-child{border-color:rgba(232,198,106,.6);background:rgba(232,198,106,.08);color:#fde68a}.asc-pdf__actions button:disabled{opacity:.45;cursor:not-allowed}.asc-pdf__note{padding:0 24px 20px;color:#64748b;font-size:9px;line-height:1.6}@media(max-width:800px){.asc-pdf__metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}`;
    document.head.appendChild(style);
  }

  function ensurePanel(){
    let panel=document.getElementById('travelPdfEngine');if(panel)return panel;
    panel=document.createElement('section');panel.id='travelPdfEngine';panel.className='asc-pdf';panel.hidden=true;panel.setAttribute('aria-labelledby','travelPdfTitle');
    panel.innerHTML=`<header class="asc-pdf__head"><p>Fase 9 · PDF ejecutivo automático</p><h2 id="travelPdfTitle">Convertir la decisión en una guía ejecutiva trazable</h2><span>Resumen → solo durante tu viaje → itinerario → logística → costos → fuentes → metodología.</span></header><div id="travelPdfStatus" class="asc-pdf__status" data-state="idle">Esperando contrato de costos de Fase 8.</div><div id="travelPdfMetrics" class="asc-pdf__metrics" hidden></div><div class="asc-pdf__actions"><button id="travelPdfPrint" type="button" disabled>Generar PDF ejecutivo</button><button id="travelPdfJson" type="button" disabled>Descargar expediente JSON</button></div><div class="asc-pdf__note">El PDF se genera con el diálogo nativo de impresión del navegador. Seleccione “Guardar como PDF”. El documento no agrega precios, eventos, reservas ni disponibilidad fuera de los contratos ya verificados por Viajes ASC.</div>`;
    (document.getElementById('travelCostEngine')||document.getElementById('travelItineraryEngine'))?.insertAdjacentElement('afterend',panel);
    panel.querySelector('#travelPdfPrint')?.addEventListener('click',printReport);
    panel.querySelector('#travelPdfJson')?.addEventListener('click',downloadJson);
    return panel;
  }
  function status(message,mode='idle'){const el=document.getElementById('travelPdfStatus');if(el){el.textContent=message;el.dataset.state=mode;}}

  function totalsText(report){const totals=report?.costs?.totals_by_currency||{};const currencies=Object.keys(totals);return currencies.length?currencies.map(cur=>money(totals[cur],cur)).join(' + '):'Sin subtotal sumable';}

  function render(report){
    const panel=ensurePanel();panel.hidden=false;const metrics=document.getElementById('travelPdfMetrics');metrics.hidden=false;
    metrics.innerHTML=`<div><span>Completitud</span><strong>${report.completeness.score}%</strong></div><div><span>Solo en fechas</span><strong>${report.only_during_trip.length}</strong></div><div><span>Fuentes</span><strong>${report.sources.length}</strong></div><div><span>Subtotal observado</span><strong>${esc(totalsText(report))}</strong></div>`;
    panel.querySelector('#travelPdfPrint').disabled=false;panel.querySelector('#travelPdfJson').disabled=false;
    status(`${report.completeness.status==='complete_evidence_package'?'Expediente completo':'Expediente parcial y trazable'} · ${report.completeness.score}% de cobertura documental · ${report.sources.length} fuente(s).`,'ready');
  }

  function activityHtml(item){const href=safeHref(item.source_url);return `<div class="item"><div><b>${esc(item.name)}</b><span>${esc(item.executive_classification||item.category||'Actividad')}</span></div><p>${esc([item.venue,item.location].filter(Boolean).join(' · ')||'Ubicación pendiente')} · Opportunity ${item.opportunity_index??'—'} · Experience ${item.asc_experience_score??'—'}</p>${href?`<a href="${esc(href)}">Fuente</a>`:''}</div>`;}
  function itineraryHtml(report){return report.itinerary.map(day=>{const selected=day.selected.map(stop=>`<div class="schedule"><strong>${esc(fmtTime(stop))}</strong><div><b>${esc(stop.name)}</b><span>${esc([stop.venue,stop.location].filter(Boolean).join(' · ')||'Ubicación pendiente')} · ${esc(stop.executive_classification||'')}</span></div></div>`).join('');const blocks=day.planning_blocks.map(block=>`<div class="planning">${esc(block.label)} · bloque genérico de planificación · sin precio/reserva</div>`).join('');return `<section class="day"><h3>${esc(fmtDate(day.date))}<small>${esc(day.verdict||'')}</small></h3>${selected||'<p class="muted">Sin actividades verificadas seleccionadas.</p>'}${blocks}</section>`}).join('');}

  function printDocument(report){
    const only=report.only_during_trip.length?report.only_during_trip.map(activityHtml).join(''):'<p class="muted">No hay oportunidades extraordinarias confirmadas que cumplan el filtro “solo durante tu viaje”.</p>';
    const costRows=report.costs.lines.length?report.costs.lines.map(line=>`<tr><td>${esc(line.category)}</td><td>${esc(line.label)}</td><td>${esc(money(line.amount,line.currency))}</td><td>${esc(line.basis)}</td><td>${line.included_in_observed_subtotal?'Sí':'No'}</td></tr>`).join(''):'<tr><td colspan="5">Sin precios observados utilizables.</td></tr>';
    const sources=report.sources.length?report.sources.map((source,index)=>`<li><span>${index+1}.</span><a href="${esc(source.url)}">${esc(source.title||source.url)}</a>${source.observed_at?`<small>${esc(source.observed_at)}</small>`:''}</li>`).join(''):'<li>Sin fuentes enlazadas.</li>';
    const maps=report.logistics.days.filter(day=>day.maps_url).map(day=>`<li>${esc(fmtDate(day.date))}: <a href="${esc(day.maps_url)}">abrir ruta</a></li>`).join('');
    const budget=report.costs.budget_comparison?`<p><b>Presupuesto:</b> ${esc(money(report.costs.budget_comparison.budget,report.costs.budget_comparison.currency))} · subtotal observado ${esc(money(report.costs.budget_comparison.observed_subtotal,report.costs.budget_comparison.currency))} · uso ${report.costs.budget_comparison.usage_pct}%.</p>`:'';
    return `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Viajes ASC - ${esc(report.trip.destination||'Guía ejecutiva')}</title><style>
      @page{size:A4;margin:14mm 13mm 15mm}*{box-sizing:border-box}body{margin:0;color:#14202b;font:10.5pt/1.45 Arial,Helvetica,sans-serif}h1,h2,h3,p{margin:0}a{color:#075985;text-decoration:none;word-break:break-word}.cover{min-height:250mm;display:flex;flex-direction:column;justify-content:space-between;padding:18mm 4mm}.brand{font-size:9pt;letter-spacing:.18em;font-weight:700;color:#a16207}.cover h1{margin-top:25mm;font-size:30pt;line-height:1.05;color:#0f172a}.cover .destination{margin-top:6mm;font-size:20pt;color:#334155}.cover .meta{margin-top:8mm;display:grid;grid-template-columns:repeat(2,1fr);gap:4mm}.metric{padding:4mm;border:1px solid #cbd5e1;border-radius:3mm}.metric span{display:block;font-size:7pt;text-transform:uppercase;letter-spacing:.1em;color:#64748b}.metric b{display:block;margin-top:1mm;font-size:13pt}.disclosure{padding:4mm;border-left:3px solid #ca8a04;background:#fffbeb;font-size:8.5pt}.page{break-before:page;padding-top:2mm}.section{margin-bottom:7mm}.section h2{padding-bottom:2mm;border-bottom:1px solid #cbd5e1;font-size:16pt}.lead{margin-top:3mm;color:#475569}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:3mm;margin-top:4mm}.item{break-inside:avoid;padding:3.5mm;border:1px solid #dbe2ea;border-radius:2mm}.item>div{display:flex;justify-content:space-between;gap:3mm}.item b{font-size:10.5pt}.item span{font-size:7.5pt;color:#92400e;text-transform:uppercase}.item p{margin-top:1.5mm;font-size:8.5pt;color:#475569}.item a{display:inline-block;margin-top:1.5mm;font-size:8pt}.day{break-inside:avoid;margin-top:4mm;border-top:1px solid #dbe2ea;padding-top:3mm}.day h3{display:flex;justify-content:space-between;font-size:12pt}.day h3 small{font-size:7.5pt;color:#64748b;text-transform:uppercase}.schedule{display:grid;grid-template-columns:30mm 1fr;gap:3mm;padding:2.5mm 0;border-bottom:1px solid #eef2f7}.schedule strong{font-size:8.5pt;color:#075985}.schedule b{display:block}.schedule span{display:block;font-size:8pt;color:#64748b}.planning{margin:2mm 0;padding:2.5mm;border:1px dashed #94a3b8;color:#64748b;font-size:8pt}.costs{width:100%;border-collapse:collapse;margin-top:3mm}.costs th,.costs td{padding:2mm;border-bottom:1px solid #e2e8f0;text-align:left;font-size:8pt}.costs th{text-transform:uppercase;color:#64748b}.sources{padding-left:0;list-style:none}.sources li{display:grid;grid-template-columns:7mm 1fr;gap:2mm;margin:2mm 0;font-size:8pt}.sources small{display:block;color:#64748b}.muted{color:#64748b}.foot{margin-top:6mm;padding-top:3mm;border-top:1px solid #cbd5e1;font-size:7.5pt;color:#64748b}.avoid{break-inside:avoid}@media print{button{display:none}}
    </style></head><body>
      <section class="cover"><div><div class="brand">VIAJES ASC · EXECUTIVE TRAVEL INTELLIGENCE</div><h1>GUÍA EJECUTIVA DE VIAJE</h1><div class="destination">${esc(report.trip.destination||'Destino por confirmar')}</div><div class="meta"><div class="metric"><span>Fechas</span><b>${esc(report.trip.start?fmtDate(report.trip.start):'Pendiente')} → ${esc(report.trip.end?fmtDate(report.trip.end):'Pendiente')}</b></div><div class="metric"><span>Viajeros</span><b>${report.trip.travelers||'—'}</b></div><div class="metric"><span>ASC Window</span><b>${report.decision.asc_travel_window_score??'—'}</b></div><div class="metric"><span>Completitud</span><b>${report.completeness.score}%</b></div></div></div><div class="disclosure"><b>Regla de integridad:</b> este documento solo reorganiza evidencia existente de Viajes ASC. Los precios unitarios o de base desconocida no forman parte del subtotal; no se aplica FX implícito; los bloques genéricos de planificación no son reservas.</div></section>
      <main class="page"><section class="section"><h2>1. Decisión ejecutiva</h2><p class="lead">${report.decision.top_opportunity?`Oportunidad principal: <b>${esc(report.decision.top_opportunity.name)}</b> · Opportunity ${report.decision.top_opportunity.opportunity_index??'—'} · ${esc(report.decision.top_opportunity.classification||'clasificación pendiente')}.`: 'Oportunidad principal pendiente de investigación verificable.'}</p><div class="grid"><div class="metric"><span>ASC Logistics</span><b>${report.decision.logistics_score??'—'}</b></div><div class="metric"><span>Actividades priorizadas</span><b>${report.decision.itinerary_activities}</b></div><div class="metric"><span>Cost coverage</span><b>${report.decision.cost_coverage??0}%</b></div><div class="metric"><span>Travel Collision</span><b>${report.decision.collision_detected?`${report.decision.collision_count} señales`:'No detectada'}</b></div></div></section>
      <section class="section"><h2>2. Solo durante tu viaje</h2><div class="grid">${only}</div></section>
      <section class="section"><h2>3. Itinerario ejecutivo</h2>${itineraryHtml(report)}</section>
      <section class="section"><h2>4. Logística</h2><p class="lead"><b>${esc(report.logistics.verdict||'Pendiente')}</b> · Logistics ${report.logistics.score??'—'} · choques ${report.logistics.impossible} · ajustes ${report.logistics.strained} · por verificar ${report.logistics.unverified}.</p>${maps?`<ul>${maps}</ul>`:'<p class="muted">No hay rutas cartográficas con evidencia suficiente.</p>'}</section>
      <section class="section"><h2>5. Costo total trazable</h2><p class="lead"><b>Subtotal observado:</b> ${esc(totalsText(report))} · cobertura ${report.costs.coverage??0}%.</p>${budget}<table class="costs"><thead><tr><th>Categoría</th><th>Concepto</th><th>Precio</th><th>Base</th><th>Sumado</th></tr></thead><tbody>${costRows}</tbody></table>${report.costs.missing_categories.length?`<p class="lead"><b>Pendiente:</b> ${esc(report.costs.missing_categories.join(' · '))}</p>`:''}</section>
      <section class="section"><h2>6. Fuentes y trazabilidad</h2><ol class="sources">${sources}</ol></section>
      <section class="section avoid"><h2>7. Metodología</h2><p class="lead">Investigación: ${esc(report.methodology.research)}.</p><p class="lead">Itinerario: ${esc(report.methodology.itinerary)}.</p><p class="lead">Logística: ${esc(report.methodology.logistics)}.</p><p class="lead">Costos: ${esc(report.methodology.costs)}.</p><div class="foot">Contrato ${esc(report.contract)} · generado ${esc(report.generated_at)} · paquete ${esc(report.completeness.status)}.</div></section></main>
    </body></html>`;
  }

  function printReport(){
    if(!state.report)return;const popup=window.open('','_blank');if(!popup){status('El navegador bloqueó la ventana del PDF. Permita pop-ups para Viajes ASC y vuelva a intentarlo.','partial');return;}
    try{popup.opener=null;}catch{}
    popup.document.open();popup.document.write(printDocument(state.report));popup.document.close();popup.focus();window.setTimeout(()=>popup.print(),250);
  }
  function downloadJson(){
    if(!state.report)return;const blob=new Blob([JSON.stringify(state.report,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`viajes-asc-${(state.report.trip.destination||'viaje').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'viaje'}-${state.report.trip.start||'sin-fecha'}.json`;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);
  }

  function build(detail={}){
    const profile=detail.profile||window.__VIAJES_ASC_ACTIVE_TRIP_PROFILE__||{};const research=detail.research||window.__VIAJES_ASC_TRAVEL_RESEARCH__||{};const logistics=detail.logistics||window.__VIAJES_ASC_LOGISTICS__||{};const itinerary=detail.itinerary||window.__VIAJES_ASC_ITINERARY__||{};const cost=detail.cost||window.__VIAJES_ASC_COST__||{};const selectedWindow=window.__VIAJES_ASC_SELECTED_WINDOW__||{};
    state.profile=profile;state.research=research;state.logistics=logistics;state.itinerary=itinerary;state.cost=cost;state.selectedWindow=selectedWindow;state.report=core.buildReport(profile,research,logistics,itinerary,cost,selectedWindow);window.__VIAJES_ASC_PDF_REPORT__=state.report;render(state.report);window.dispatchEvent(new CustomEvent('viajes:pdf-ready',{detail:{profile,research,logistics,itinerary,cost,selectedWindow,report:state.report}}));
  }

  styles();ensurePanel();
  window.addEventListener('viajes:cost-ready',event=>build(event.detail||{}));
  window.TravelPdf={build,getReport:()=>state.report,print:printReport,downloadJson};
})();
